sudo: required
services:
  - docker

before_install:
  - docker build -t gli68/docker-react -f Dockerfile.dev .

script:
#  - docker run -e CI=true gli68/docker-react npm run test 
  - docker run gli68/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "DockerReact-env-1"
  bucket_name: "aw-dms"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY




